/**
 * @file PluginInit.cpp
 * @brief Plugin entry point — the single compiled translation unit.
 *
 * WHY THIS IS A COMMITTED SOURCE FILE (not generated by CMake)
 * ─────────────────────────────────────────────────────────────
 * The previous design used file(WRITE ...) in CMakeLists.txt to generate
 * this file at configure time.  That approach has two problems:
 *
 *  1. file(WRITE) runs during cmake configuration, not during the build.
 *     Changes to VolterraProcessor.h are tracked by the compiler's implicit
 *     dependency scanner (so recompilation does trigger correctly), but the
 *     generated file itself is only updated when CMake re-runs — making the
 *     approach fragile if the generated content ever needs to reflect CMake
 *     variables (e.g., plugin name, version strings).
 *
 *  2. Generating a file whose content never varies based on CMake state is
 *     pure overhead.  configure_file() is the right tool when substitution
 *     is needed; file(WRITE) with static content just adds indirection.
 *
 * This file is intentionally minimal.  All plugin logic lives in
 * VolterraProcessor.h (the AudioProcessor subclass) and PrunedVolterraFilter.h
 * (the DSP core).  The CUDA paths are conditionally compiled via the
 * VOLTERRA_CUDA_AVAILABLE preprocessor guard set by CMakeLists.txt.
 *
 * DEPENDENCY TRACKING
 * ────────────────────
 * Because this .cpp directly #includes VolterraProcessor.h, the compiler's
 * implicit dependency scanner registers a make/ninja dependency:
 *
 *   PluginInit.cpp.o depends on VolterraProcessor.h
 *                              → PrunedVolterraFilter.h (transitive)
 *                              → VolterraCUDAProcessor.h (if CUDA enabled)
 *                              → VolterraKernels.cuh (transitive)
 *
 * Touching any file in that chain causes PluginInit.cpp to recompile on the
 * next incremental build without any manual CMake re-run.
 *
 * createPluginFilter() is documented at:
 *   https://docs.juce.com/master/classjuce_1_1AudioProcessor.html
 */

// VolterraEditor.h includes VolterraProcessor.h, so include only the editor here.
#include "VolterraEditor.h"

juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new VolterraProcessor();
}

// Defined here so VolterraProcessor.h doesn't need to include VolterraEditor.h,
// keeping the two headers free of a circular dependency.
juce::AudioProcessorEditor* VolterraProcessor::createEditor()
{
    return new VolterraEditor (*this);
}
