#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <juce_gui_basics/juce_gui_basics.h>
#include <juce_graphics/juce_graphics.h>

#include <BinaryData.h>   // embedded assets — generated by juce_add_binary_data

#include "VolterraProcessor.h"
#include "VolterraPresets.h"

// ─────────────────────────────────────────────────────────────────────────────
//  VoltLookAndFeel — hardware-style dark knobs and combo box
// ─────────────────────────────────────────────────────────────────────────────

class VoltLookAndFeel final : public juce::LookAndFeel_V4
{
public:
    VoltLookAndFeel()
    {
        setColour (juce::ComboBox::backgroundColourId,                 juce::Colour (0xff222232));
        setColour (juce::ComboBox::textColourId,                       juce::Colour (0xffbbbbcc));
        setColour (juce::ComboBox::outlineColourId,                    juce::Colour (0xff404055));
        setColour (juce::ComboBox::arrowColourId,                      juce::Colour (0xff6688ff));
        setColour (juce::PopupMenu::backgroundColourId,                juce::Colour (0xff222232));
        setColour (juce::PopupMenu::textColourId,                      juce::Colour (0xffbbbbcc));
        setColour (juce::PopupMenu::highlightedBackgroundColourId,     juce::Colour (0xff3a3a5a));
        setColour (juce::PopupMenu::highlightedTextColourId,           juce::Colour (0xffffffff));
        setColour (juce::Label::textColourId,                          juce::Colour (0xff8888aa));
        setColour (juce::Slider::textBoxTextColourId,                  juce::Colour (0xff9999bb));
        setColour (juce::Slider::textBoxBackgroundColourId,            juce::Colours::transparentBlack);
        setColour (juce::Slider::textBoxOutlineColourId,               juce::Colours::transparentBlack);
        setColour (juce::Slider::textBoxHighlightColourId,             juce::Colour (0xff3a3a5a));
    }

    void drawRotarySlider (juce::Graphics& g,
                           int x, int y, int width, int height,
                           float sliderPosProportional,
                           float rotaryStartAngle, float rotaryEndAngle,
                           juce::Slider&) override
    {
        const float outerR = juce::jmin (width, height) * 0.5f - 5.0f;
        const float cx = x + width  * 0.5f;
        const float cy = y + height * 0.5f;

        // Shadow ring
        g.setColour (juce::Colour (0x30000000));
        g.fillEllipse (cx - outerR - 3, cy - outerR - 3,
                       (outerR + 3) * 2, (outerR + 3) * 2);

        // Track arc (full range)
        {
            juce::Path track;
            track.addCentredArc (cx, cy, outerR, outerR, 0.0f,
                                 rotaryStartAngle, rotaryEndAngle, true);
            g.setColour (juce::Colour (0xff2a2a3a));
            g.strokePath (track, juce::PathStrokeType (5.0f,
                          juce::PathStrokeType::curved,
                          juce::PathStrokeType::rounded));
        }

        // Value arc (filled portion)
        {
            const float angle = rotaryStartAngle
                                + sliderPosProportional * (rotaryEndAngle - rotaryStartAngle);
            juce::Path val;
            val.addCentredArc (cx, cy, outerR, outerR, 0.0f,
                               rotaryStartAngle, angle, true);

            juce::ColourGradient grad (juce::Colour (0xff4477ff),
                                       cx - outerR, cy,
                                       juce::Colour (0xff88bbff),
                                       cx + outerR, cy, false);
            g.setGradientFill (grad);
            g.strokePath (val, juce::PathStrokeType (5.0f,
                          juce::PathStrokeType::curved,
                          juce::PathStrokeType::rounded));
        }

        // Knob body
        const float bodyR = outerR * 0.62f;
        {
            juce::ColourGradient bodyGrad (juce::Colour (0xff28283c),
                                           cx, cy - bodyR,
                                           juce::Colour (0xff1a1a28),
                                           cx, cy + bodyR, false);
            g.setGradientFill (bodyGrad);
            g.fillEllipse (cx - bodyR, cy - bodyR, bodyR * 2, bodyR * 2);
        }

        g.setColour (juce::Colour (0xff404058));
        g.drawEllipse (cx - bodyR, cy - bodyR, bodyR * 2, bodyR * 2, 1.2f);

        // Pointer line + tip dot
        {
            const float angle = rotaryStartAngle
                                + sliderPosProportional * (rotaryEndAngle - rotaryStartAngle)
                                - juce::MathConstants<float>::halfPi;
            const float innerR = bodyR * 0.25f;
            const float tipR   = bodyR * 0.82f;

            g.setColour (juce::Colour (0xffccccdd));
            g.drawLine (cx + innerR * std::cos (angle), cy + innerR * std::sin (angle),
                        cx + tipR   * std::cos (angle), cy + tipR   * std::sin (angle), 2.2f);

            const float dotR = 3.5f;
            g.setColour (juce::Colour (0xff7799ff));
            g.fillEllipse (cx + tipR * std::cos (angle) - dotR,
                           cy + tipR * std::sin (angle) - dotR,
                           dotR * 2.0f, dotR * 2.0f);
        }
    }

    void drawComboBox (juce::Graphics& g, int width, int height,
                       bool /*isButtonDown*/, int buttonX, int buttonY,
                       int buttonW, int buttonH, juce::ComboBox& box) override
    {
        const auto bounds = juce::Rectangle<float> (0, 0, (float) width, (float) height);
        g.setColour (box.findColour (juce::ComboBox::backgroundColourId));
        g.fillRoundedRectangle (bounds, 4.0f);
        g.setColour (box.findColour (juce::ComboBox::outlineColourId));
        g.drawRoundedRectangle (bounds.reduced (0.5f), 4.0f, 1.0f);

        // Arrow
        juce::Path arrow;
        const float aX = buttonX + buttonW * 0.5f;
        const float aY = buttonY + buttonH * 0.5f;
        arrow.addTriangle (aX - 5, aY - 2, aX + 5, aY - 2, aX, aY + 4);
        g.setColour (box.findColour (juce::ComboBox::arrowColourId));
        g.fillPath (arrow);
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  VolterraEditor
// ─────────────────────────────────────────────────────────────────────────────

class VolterraEditor final : public juce::AudioProcessorEditor,
                             private juce::Timer
{
public:
    explicit VolterraEditor (VolterraProcessor& p)
        : AudioProcessorEditor (p),
          processor_ (p),
          backgroundImage_ (juce::ImageCache::getFromMemory (
              BinaryData::background_png, BinaryData::background_pngSize)),
          driveAttach_  (p.getAPVTS(), "drive",  driveKnob_),
          mixAttach_    (p.getAPVTS(), "mix",    mixKnob_),
          outputAttach_ (p.getAPVTS(), "output", outputKnob_)
    {

        setLookAndFeel (&lf_);

        // ── Knobs ──────────────────────────────────────────────────────────────
        for (auto* knob : { &driveKnob_, &mixKnob_, &outputKnob_ })
        {
            knob->setSliderStyle (juce::Slider::RotaryVerticalDrag);
            knob->setTextBoxStyle (juce::Slider::TextBoxBelow, false, 72, 18);
            addAndMakeVisible (knob);
        }

        // ── Knob labels ────────────────────────────────────────────────────────
        for (auto [lbl, text] : { std::pair{ &driveLabel_,  "DRIVE"  },
                                  std::pair{ &mixLabel_,    "MIX"    },
                                  std::pair{ &outputLabel_, "OUTPUT" } })
        {
            lbl->setText (text, juce::dontSendNotification);
            lbl->setFont (juce::Font (juce::FontOptions (10.5f)).boldened());
            lbl->setJustificationType (juce::Justification::centred);
            addAndMakeVisible (lbl);
        }

        // ── Preset combo ────────────────────────────────────────────────────────
        presetBox_.addItem ("-- Custom --", 1);
        for (int i = 0; i < static_cast<int> (VolterraPresets::Id::kCount); ++i)
            presetBox_.addItem (VolterraPresets::name (static_cast<VolterraPresets::Id> (i)),
                                i + 2);

        presetBox_.setSelectedId (1, juce::dontSendNotification);
        presetBox_.onChange = [this] { onPresetSelected(); };
        addAndMakeVisible (presetBox_);

        startTimerHz (10);   // repaint footer CUDA/CPU indicator
        setSize (560, 300);
        setResizable (false, false);
    }

    ~VolterraEditor() override
    {
        stopTimer();
        setLookAndFeel (nullptr);
    }

    // ── Paint ──────────────────────────────────────────────────────────────────

    void paint (juce::Graphics& g) override
    {
        // ── Background image ──────────────────────────────────────────────────
        if (backgroundImage_.isValid())
        {
            // Draw scaled to fill; the image is 16:9 which matches the 560:300
            // window closely enough that cropping is minimal.
            g.drawImage (backgroundImage_,
                         getLocalBounds().toFloat(),
                         juce::RectanglePlacement::fillDestination);

            // Dark tint over the whole surface to keep the image from competing
            // with UI text and knobs.
            g.setColour (juce::Colour (0x99000000));
            g.fillAll();
        }
        else
        {
            g.fillAll (juce::Colour (0xff1a1a2a));   // fallback if asset missing
        }

        // Header strip — semi-transparent so the background shows through.
        g.setColour (juce::Colour (0xee0d0d1a));
        g.fillRect (0, 0, getWidth(), kHeaderH);

        // Footer strip
        g.setColour (juce::Colour (0xee0d0d1a));
        g.fillRect (0, getHeight() - kFooterH, getWidth(), kFooterH);

        // Separator lines
        g.setColour (juce::Colour (0xff333355));
        g.fillRect (0, kHeaderH, getWidth(), 1);
        g.fillRect (0, getHeight() - kFooterH, getWidth(), 1);

        // Title
        g.setFont (juce::Font (juce::FontOptions (17.0f)).boldened());
        g.setColour (juce::Colour (0xffddddee));
        g.drawText ("VOLTERRA NL FILTER",
                    14, 0, 280, kHeaderH,
                    juce::Justification::centredLeft);

        // Subtitle / version
        g.setFont (juce::Font (juce::FontOptions (9.5f)));
        g.setColour (juce::Colour (0xff444466));
        g.drawText ("3rd-Order Memory Polynomial  v1.0.0",
                    14, 0, 300, kHeaderH,
                    juce::Justification::bottomLeft);

        // Footer: company
        g.setFont (juce::Font (juce::FontOptions (9.5f)));
        g.setColour (juce::Colour (0xff444466));
        g.drawText ("VoltDSP",
                    10, getHeight() - kFooterH, 80, kFooterH,
                    juce::Justification::centredLeft);

        // Footer: CUDA / CPU badge
        drawStatusBadge (g);
    }

    void resized() override
    {
        // Preset combo — top-right of header
        presetBox_.setBounds (getWidth() - 200, 10, 188, 30);

        // Knob zone geometry
        const int zones = 3;
        const int zoneW = getWidth() / zones;
        const int contentH = getHeight() - kHeaderH - kFooterH;
        const int totalH   = kLabelH + kKnobH;
        const int topPad   = (contentH - totalH) / 2;
        const int labelY   = kHeaderH + topPad;
        const int knobY    = labelY + kLabelH;

        juce::Slider* knobs[]  = { &driveKnob_, &mixKnob_, &outputKnob_ };
        juce::Label*  labels[] = { &driveLabel_, &mixLabel_, &outputLabel_ };

        for (int i = 0; i < zones; ++i)
        {
            const int cx = zoneW * i + zoneW / 2;
            labels[i]->setBounds (cx - 40, labelY, 80, kLabelH);
            knobs [i]->setBounds (cx - kKnobW / 2, knobY, kKnobW, kKnobH);
        }
    }

private:
    // ── Timer ─────────────────────────────────────────────────────────────────

    void timerCallback() override
    {
        repaint (0, getHeight() - kFooterH, getWidth(), kFooterH);
    }

    // ── Preset selection ───────────────────────────────────────────────────────

    void onPresetSelected()
    {
        const int id = presetBox_.getSelectedId();
        if (id <= 1) return;

        const auto pid = static_cast<VolterraPresets::Id> (id - 2);
        float h1[kMemoryLength], h2[kMemoryLength], h3[kMemoryLength];
        VolterraPresets::build (pid, h1, h2, h3);
        processor_.setKernels (h1, h2, h3);
    }

    // ── CUDA / CPU status badge ────────────────────────────────────────────────

    void drawStatusBadge (juce::Graphics& g)
    {
#ifdef VOLTERRA_CUDA_AVAILABLE
        const bool cuda = processor_.isCUDAActive();
        const juce::Colour dotCol = cuda ? juce::Colour (0xff33cc77)
                                         : juce::Colour (0xff555566);
        const juce::String label  = cuda ? "CUDA" : "CPU";
#else
        const juce::Colour dotCol  = juce::Colour (0xff555566);
        const juce::String label   = "CPU";
#endif
        const int fy = getHeight() - kFooterH;
        const int fx = getWidth() - 68;

        g.setColour (dotCol);
        g.fillEllipse ((float) fx, (float) (fy + kFooterH / 2) - 4.0f, 8.0f, 8.0f);

        g.setFont (juce::Font (juce::FontOptions (9.5f)));
        g.setColour (dotCol);
        g.drawText (label, fx + 12, fy, 50, kFooterH, juce::Justification::centredLeft);
    }

    // ── Constants ──────────────────────────────────────────────────────────────

    static constexpr int kHeaderH = 50;
    static constexpr int kFooterH = 24;
    static constexpr int kLabelH  = 16;
    static constexpr int kKnobW   = 110;
    static constexpr int kKnobH   = 120;   // includes TextBoxBelow

    // ── Members ────────────────────────────────────────────────────────────────

    VolterraProcessor& processor_;
    VoltLookAndFeel    lf_;
    juce::Image        backgroundImage_;   // loaded from BinaryData::background_png

    // Sliders declared before attachments — JUCE requires sliders to exist
    // when SliderAttachment is constructed.
    juce::Slider   driveKnob_, mixKnob_, outputKnob_;
    juce::Label    driveLabel_, mixLabel_, outputLabel_;
    juce::ComboBox presetBox_;

    juce::AudioProcessorValueTreeState::SliderAttachment
        driveAttach_, mixAttach_, outputAttach_;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (VolterraEditor)
};
